import type { Booking, EventDetail, FullSchedule, PaginatedEvents, Speaker } from "./types";

const DAY1_DATE = "2026-10-24";
const DAY2_DATE = "2026-10-25";

export const DEMO_SPEAKERS: Speaker[] = [
  {
    id: "spk-1",
    event_id: "devsummit-2026",
    name: "Dr. Elena Rostova",
    role_title: "VP of AI Systems",
    company: "DeepMind Labs",
    bio: "Author of 'Autonomous Agent Architectures'. Elena leads foundation model research focused on multi-agent collaboration and reasoning trees.",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    github_url: "https://github.com/erostova",
    twitter_url: "https://x.com/elena_ai",
    linkedin_url: "https://linkedin.com/in/elena-rostova",
  },
  {
    id: "spk-2",
    event_id: "devsummit-2026",
    name: "Marcus Chen",
    role_title: "Principal Distributed Systems Architect",
    company: "CloudScale Global",
    bio: "Veteran engineer responsible for scaling event streaming pipelines to over 10 million messages per second across multi-region clusters.",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    github_url: "https://github.com/marcuschen",
    twitter_url: "https://x.com/marcus_dist",
    linkedin_url: "https://linkedin.com/in/marcus-chen-dist",
  },
  {
    id: "spk-3",
    event_id: "devsummit-2026",
    name: "Sarah Jenkins",
    role_title: "Core Maintainer & Systems Engineer",
    company: "Rust Foundation & HyperFlow",
    bio: "Creator of popular asynchronous network runtimes and passionate advocate for memory-safe, zero-overhead systems programming.",
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
    github_url: "https://github.com/sjenkins-dev",
    twitter_url: "https://x.com/sarah_rust",
    linkedin_url: "https://linkedin.com/in/sarah-jenkins-dev",
  },
  {
    id: "spk-4",
    event_id: "devsummit-2026",
    name: "Alex Rivera",
    role_title: "Staff AI Infrastructure Engineer",
    company: "Anthropic Systems",
    bio: "Alex specializes in low-latency vector databases, caching tiers, and context window optimization for production enterprise copilots.",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    github_url: "https://github.com/arivera-ai",
    twitter_url: "https://x.com/alexrivera",
    linkedin_url: "https://linkedin.com/in/alex-rivera-systems",
  },
  {
    id: "spk-5",
    event_id: "devsummit-2026",
    name: "Priya Sharma",
    role_title: "Head of Database Reliability",
    company: "NexaFin Tech",
    bio: "Priya designs zero-downtime data migration strategies and active-active replication models for mission-critical financial applications.",
    avatar_url: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80",
    github_url: "https://github.com/psharma-db",
    twitter_url: "https://x.com/priyasharma_db",
    linkedin_url: "https://linkedin.com/in/priya-sharma-db",
  },
  {
    id: "spk-6",
    event_id: "devsummit-2026",
    name: "David Thorne",
    role_title: "Lead Container Engineer",
    company: "KubeForge Technologies",
    bio: "Maintainer of multiple CNCF cloud-native tools, focused on eBPF telemetry, service meshes, and custom Kubernetes operator development.",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    github_url: "https://github.com/dthorne-kube",
    twitter_url: "https://x.com/david_k8s",
    linkedin_url: "https://linkedin.com/in/davidthorne-k8s",
  },
];

export const DEMO_EVENT: EventDetail = {
  id: "devsummit-2026",
  organizer_id: "org-devsummit-001",
  title: "DevSummit 2026: Global Developer & AI Conference",
  slug: "devsummit-2026-global",
  description:
    "DevSummit 2026 brings together 2,500+ software architects, engineers, and researchers for 2 packed days of cutting-edge keynotes, multi-track deep dives into Generative AI, distributed systems, high-concurrency microservices, and interactive hands-on coding workshops.",
  category: "TECH",
  status: "PUBLISHED",
  cover_image_url: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1600&q=80",
  venue_name: "Metropolitan Tech Pavilion & Convention Center",
  venue_address: "742 Innovation Way, SOMA District",
  city: "San Francisco, CA",
  starts_at: `${DAY1_DATE}T09:00:00Z`,
  ends_at: `${DAY2_DATE}T18:00:00Z`,
  created_at: "2026-01-01T00:00:00Z",
  ticket_types: [
    {
      id: "tt-1",
      name: "General Attendee Pass",
      description: "Access to all keynotes and Track A & B sessions, conference lunch, and attendee swag bag.",
      price: "199.00",
      quantity_total: 1200,
      quantity_available: 842,
      sale_starts_at: "2026-01-01T00:00:00Z",
      sale_ends_at: `${DAY1_DATE}T08:00:00Z`,
    },
    {
      id: "tt-2",
      name: "VIP All-Access Pass",
      description: "All keynotes & tracks, reserved front-row seating, VIP lounge catering, and invitation to the Speaker Dinner.",
      price: "399.00",
      quantity_total: 250,
      quantity_available: 48,
      sale_starts_at: "2026-01-01T00:00:00Z",
      sale_ends_at: `${DAY1_DATE}T08:00:00Z`,
    },
    {
      id: "tt-3",
      name: "Hands-on Workshop Pass",
      description: "Full-day intensive bring-your-own-laptop interactive labs in Track C with direct mentor feedback.",
      price: "299.00",
      quantity_total: 300,
      quantity_available: 112,
      sale_starts_at: "2026-01-01T00:00:00Z",
      sale_ends_at: `${DAY1_DATE}T08:00:00Z`,
    },
    {
      id: "tt-4",
      name: "Student / Academic Pass",
      description: "Subsidized full conference pass for enrolled undergraduate and graduate students.",
      price: "49.00",
      quantity_total: 200,
      quantity_available: 65,
      sale_starts_at: "2026-01-01T00:00:00Z",
      sale_ends_at: `${DAY1_DATE}T08:00:00Z`,
    },
  ],
  tracks: [
    {
      id: "tr-1",
      event_id: "devsummit-2026",
      name: "Track A: Generative AI & Autonomous Agents",
      description: "Autonomous multi-agent swarms, LLM fine-tuning, RAG architectures, and production neural search.",
      room_location: "Main Auditorium (Hall 1)",
      color_code: "#6366F1",
      order: 1,
    },
    {
      id: "tr-2",
      event_id: "devsummit-2026",
      name: "Track B: Distributed Systems & Cloud Native",
      description: "High-throughput microservices, event-driven messaging, consensus protocols, and Kubernetes at scale.",
      room_location: "Innovation Hall (Room 202)",
      color_code: "#06B6D4",
      order: 2,
    },
    {
      id: "tr-3",
      event_id: "devsummit-2026",
      name: "Track C: Hands-on Workshops & Deep Dives",
      description: "Interactive coding laboratories with live debugging, load testing, and architectural refactoring.",
      room_location: "Hacker Lab (Room 305)",
      color_code: "#10B981",
      order: 3,
    },
  ],
  speakers: DEMO_SPEAKERS,
};

export const DEMO_PAGINATED_EVENTS: PaginatedEvents = {
  items: [
    {
      id: DEMO_EVENT.id,
      organizer_id: DEMO_EVENT.organizer_id,
      title: DEMO_EVENT.title,
      slug: DEMO_EVENT.slug,
      category: DEMO_EVENT.category,
      status: DEMO_EVENT.status,
      cover_image_url: DEMO_EVENT.cover_image_url,
      city: DEMO_EVENT.city,
      starts_at: DEMO_EVENT.starts_at,
      min_price: "49.00",
      max_price: "399.00",
    },
  ],
  total: 1,
  page: 1,
  page_size: 6,
};

export const DEMO_SCHEDULE: FullSchedule = {
  event_id: "devsummit-2026",
  event_title: "DevSummit 2026: Global Developer & AI Conference",
  days: [
    {
      date: DAY1_DATE,
      date_label: "Day 1 — Keynotes & Distributed Systems",
      tracks: DEMO_EVENT.tracks || [],
      slots: [
        {
          time_label: "09:30 AM - 10:45 AM",
          start_time: `${DAY1_DATE}T09:30:00Z`,
          end_time: `${DAY1_DATE}T10:45:00Z`,
          sessions: [
            {
              id: "sess-1",
              event_id: "devsummit-2026",
              track_id: "tr-1",
              speaker_id: "spk-1",
              title: "Opening Keynote: The Dawn of Autonomous Cognitive Systems",
              abstract:
                "An eye-opening kickoff exploring how foundation models are transitioning from passive chat interfaces to self-orchestrating multi-agent networks that plan, write code, verify logic, and deploy resilient services.",
              session_type: "KEYNOTE",
              start_time: `${DAY1_DATE}T09:30:00Z`,
              end_time: `${DAY1_DATE}T10:45:00Z`,
              track: DEMO_EVENT.tracks?.[0],
              speaker: DEMO_SPEAKERS[0],
            },
          ],
        },
        {
          time_label: "11:00 AM - 12:15 PM",
          start_time: `${DAY1_DATE}T11:00:00Z`,
          end_time: `${DAY1_DATE}T12:15:00Z`,
          sessions: [
            {
              id: "sess-2",
              event_id: "devsummit-2026",
              track_id: "tr-1",
              speaker_id: "spk-4",
              title: "Building Production-Grade RAG: Beyond Naive Vector Search",
              abstract:
                "Deep dive into semantic chunking, reciprocal rank fusion (RRF), re-ranking models, and Redis caching layers to build retrieval-augmented generation pipelines that execute in under 120ms.",
              session_type: "TALK",
              start_time: `${DAY1_DATE}T11:00:00Z`,
              end_time: `${DAY1_DATE}T12:15:00Z`,
              track: DEMO_EVENT.tracks?.[0],
              speaker: DEMO_SPEAKERS[3],
            },
            {
              id: "sess-3",
              event_id: "devsummit-2026",
              track_id: "tr-2",
              speaker_id: "spk-2",
              title: "Architecting Resilient Event Streams with RabbitMQ & Outbox Pattern",
              abstract:
                "Learn how to eliminate split-brain states and dual-write data inconsistencies between microservices using transactional outbox patterns, idempotent consumers, and backpressure monitoring.",
              session_type: "TALK",
              start_time: `${DAY1_DATE}T11:00:00Z`,
              end_time: `${DAY1_DATE}T12:15:00Z`,
              track: DEMO_EVENT.tracks?.[1],
              speaker: DEMO_SPEAKERS[1],
            },
            {
              id: "sess-4",
              event_id: "devsummit-2026",
              track_id: "tr-3",
              speaker_id: "spk-3",
              title: "Workshop Lab: Writing High-Performance Rust Microservices from Scratch",
              abstract:
                "Bring your laptop! In this intensive hands-on lab, we build an asynchronous HTTP service using Axum/Tokio, implement connection pooling, and benchmark throughput against equivalent Node.js services.",
              session_type: "WORKSHOP",
              start_time: `${DAY1_DATE}T11:00:00Z`,
              end_time: `${DAY1_DATE}T14:00:00Z`,
              track: DEMO_EVENT.tracks?.[2],
              speaker: DEMO_SPEAKERS[2],
            },
          ],
        },
      ],
    },
    {
      date: DAY2_DATE,
      date_label: "Day 2 — Deep Dives & Hands-on Labs",
      tracks: DEMO_EVENT.tracks || [],
      slots: [
        {
          time_label: "10:00 AM - 11:30 AM",
          start_time: `${DAY2_DATE}T10:00:00Z`,
          end_time: `${DAY2_DATE}T11:30:00Z`,
          sessions: [
            {
              id: "sess-5",
              event_id: "devsummit-2026",
              track_id: "tr-2",
              speaker_id: "spk-5",
              title: "Zero-Downtime PostgreSQL Migrations for Sharded Microservices",
              abstract:
                "Field-tested patterns for online schema migrations, column deprecation, lock management, and replica synchronization in high-concurrency relational architectures.",
              session_type: "TALK",
              start_time: `${DAY2_DATE}T10:00:00Z`,
              end_time: `${DAY2_DATE}T11:30:00Z`,
              track: DEMO_EVENT.tracks?.[1],
              speaker: DEMO_SPEAKERS[4],
            },
            {
              id: "sess-6",
              event_id: "devsummit-2026",
              track_id: "tr-3",
              speaker_id: "spk-1",
              title: "Workshop Lab: Building Multi-Agent Systems with Guardrails",
              abstract:
                "Hands-on workshop configuring agent hierarchies, tool dispatching, loop prevention, and schema enforcement using open standards and local LLMs.",
              session_type: "WORKSHOP",
              start_time: `${DAY2_DATE}T10:00:00Z`,
              end_time: `${DAY2_DATE}T13:00:00Z`,
              track: DEMO_EVENT.tracks?.[2],
              speaker: DEMO_SPEAKERS[0],
            },
          ],
        },
      ],
    },
  ],
};

export const DEMO_BOOKINGS: Booking[] = [
  {
    id: "bk-984210",
    reservation_id: "res-789a2b",
    user_id: "user-demo",
    event_id: "devsummit-2026",
    organizer_id: "org-devsummit-001",
    status: "CONFIRMED",
    total_amount: "399.00",
    expires_at: null,
    created_at: "2026-09-01T10:30:00Z",
    items: [
      {
        id: "item-1",
        ticket_type_id: "tt-2",
        ticket_type_name: "VIP All-Access Pass",
        unit_price: "399.00",
        quantity: 1,
      },
    ],
  },
];
